apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "order-service.fullname" . }}-destination-rule
spec:
  host: {{ include "order-service.fullname" . }}
  subsets:
  - name: v1
    labels:
      version: v1
