apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  gateways:
    - {{ include "order-service.fullname" . }}-gateway
  hosts:
    - exchange.memoryforcer.com
  http:
    - match:
        - uri:
            prefix: /api/v1/orders
      route:
      - destination:
          host: {{ include "order-service.fullname" . }}
          port:
            number: 9292
