version: '3'
services:
  # STAGE 1 ================================================
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # STAGE 2 ================================================
  db-migrator:
    build: ./db-migrator
    command: 
      - /bin/bash 
      - -c 
      - sleep 3 && bundle exec rake db:create; bundle exec rake db:migrate; bundle exec rake db:seed
    environment:
      ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
  # STAGE 3 ================================================
  auth-service:
    build: ./auth-service
    command:
      - /bin/ash 
      - -c 
      - bundle exec rackup
    environment:
      RACK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db-migrator
    ports:
      - "3000:9292"
  account-service:
    build: ./account-service
    command:
      - /bin/ash 
      - -c 
      - bundle exec rackup
    environment:
      RACK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db-migrator
    ports:
      - "3001:9292"
  order-service:
    build: ./order-service
    command:
      - /bin/ash 
      - -c 
      - bundle exec rackup
    environment:
      RACK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db-migrator
    ports:
      - "3002:9292"
  trade-service:
    build: ./trade-service
    command:
      - /bin/ash 
      - -c 
      - bundle exec rackup
    environment:
      RACK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db-migrator
    ports:
      - "3003:9292"
  # STAGE 4 ================================================
  e2e-test:
    build: ./e2e-test
    command:
      - /bin/ash 
      - -c 
      - sleep 5; bundle exec rake
    environment:
      RACK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - auth-service
      - account-service
      - order-service
      - trade-service
