apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migrator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "db-migrator.name" . }}
    helm.sh/chart: {{ include "db-migrator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          command:
            - /bin/bash
            - -c
            - until pg_isready -h {{ .Release.Name }}-postgresql -p 5432; do echo waiting for database; sleep 1; done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash 
            - -c 
            - bundle exec rake db:create; bundle exec rake db:migrate; bundle exec rake db:seed
          env:
            - name: ENV
              value: production
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
