apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migrator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "db-migrator.name" . }}
    helm.sh/chart: {{ include "db-migrator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          command:
            - /bin/bash
            - -c
            - until pg_isready -h {{ .Values.db.host }} -p 5432; do echo waiting for database; sleep 1; done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash 
            - -c 
            - bundle exec rake db:create; bundle exec rake db:migrate; bundle exec rake db:seed
          env:
            - name: ENV
              value: production
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: {{ .Values.db.port }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/database.yml
              subPath: database.yml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "db-migrator.fullname" . }}-configmap
