require "bundler/setup"
require "active_record"
require "yaml"

task :default => :test
task :environment do
  config = YAML.load_file("database.yml")[ENV["RACK_ENV"]]
  ActiveRecord::Base.establish_connection(config)
end

task :test => :environment do
  require "./test/app_test.rb"
end
