apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-configmap
  version: {{ .Values.image.tag }}
data:
  {{- (tpl (.Files.Glob "configs/*").AsConfig .) | nindent 2 }}
