apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "auth-service.fullname" . }}-destination-rule
spec:
  host: {{ include "auth-service.fullname" . }}
  # subsets:
  # - name: v1
  #   labels:
  #     version: v1
  # - name: v2
  #   labels:
  #     version: v2

  # trafficPolicy:
  #   loadBalancer:
  #     simple: RANDOM # ROUND_ROBIN
  #   connectionPool:
  #     tcp:
  #       maxConnections: 100 # Max 100 conns, then circuit breaking.
  #     http:
  #       http1MaxPendingRequests: 1
  #       maxRequestsPerConnection: 1
  #   outlierDetection:
  #     consecutiveErrors: 1
  #     interval: 1s
  #     baseEjectionTime: 3m
  #     maxEjectionPercent: 100
