apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  gateways:
    - {{ include "auth-service.fullname" . }}-gateway
  hosts:
    - exchange.memoryforcer.com
  http:
    - route:
      - destination:
          host: {{ include "auth-service.fullname" . }}
          port:
            number: 9292
          subset: v1
        weight: 80
      - destination:
          host: {{ include "auth-service.fullname" . }}
          port:
            number: 9292
          subset: v2
        weight: 20
