apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  gateways:
    - {{ include "auth-service.fullname" . }}-gateway
  hosts:
    - exchange.memoryforcer.com
  http:
    - route:
      - destination:
          host: {{ include "auth-service.fullname" . }}
          port:
            number: 9292
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: {{ include "auth-service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
# spec:
#   gateways:
#     - {{ include "auth-service.fullname" . }}-gateway
#   hosts:
#     - {{ include "auth-service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
#   http:
#     - route:
#       - destination:
#           host: {{ include "auth-service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
#           port:
#             number: 9292
