auth-service:
  enabled: true

account-service:
  enabled: true

order-service:
  enabled: true

trade-service:
  enabled: true

e2e-test:
  enabled: true

db-migrator:
  enabled: true

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  pgHbaConfiguration: |-
    local all all trust
    host all all localhost trust
