source "https://gems.ruby-china.com"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'rails', "~> 5.2.0"
gem 'activerecord', "~> 5.2.0"
gem 'bcrypt', ">= 3.1.12"
gem 'pg'
gem 'pry'

group :development, :test do  
  gem 'rspec'
  gem 'rspec-rails'
end
