apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "account-service.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - exchange.memoryforcer.com
        - "*.exchange.memoryforcer.com"
      # tls:
      #   httpsRedirect: true
    # - port:
    #     number: 443
    #     name: https
    #     protocol: HTTPS
    #   tls:
    #     mode: SIMPLE
    #     serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
    #     privateKey: /etc/istio/ingressgateway-certs/tls.key
    #   hosts:
    #     - "*"
    #     - istio.memoryforcer.com
    #     - exchange.memoryforcer.com
